OPENAI_API_KEY = "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"
DB_HOST = "104.196.119.128"
DB_PORT = "5432"
DATABASE = "postgres"
USER = "postgres-user"
PASSWORD = "zqA#q>pv`h3UG.XH"